parameters:
#    lansole_pages.example.class: Lansole\PagesBundle\Example

services:
    twig.extension.pages:
        class: Lansole\PagesBundle\Twig\PagesExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }